version: "3.8"

services:
  service-one:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-one
    networks:
      - app-network
  # -----------------------------------------
  service-two:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-two
    networks:
      - app-network
  # -----------------------------------------
  service-three:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-three
    networks:
      - app-network
  # -----------------------------------------
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-one
      - service-two
      - service-three
    networks:
      - app-network
  # -----------------------------------------
  k6:
    image: grafana/k6:latest
    volumes:
      - ./k6:/scripts
    entrypoint: ["k6", "run", "/scripts/spike.js"]
    depends_on:
      - load-balancer
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
