services:
  service-one:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-one
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    networks:
      - app-network
  # -----------------------------------------
  service-two:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-two
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318/v1/traces
    networks:
      - app-network
  # -----------------------------------------
  service-three:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      INSTANCE_NAME: express-three
      DATABASE_URL: postgres://postgres:password@database:5432/mydatabase
      REDIS_URL: redis://redis:6379
      
    networks:
      - app-network
  # -----------------------------------------
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - service-one
      - service-two
      - service-three
    networks:
      - app-network
  # -----------------------------------------
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  # -----------------------------------------
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    # -----------------------------------------
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network
    # -----------------------------------------
  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - app-network
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
